# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging CD

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST_CAPACITOR_STAGE }}
        username: ${{ secrets.USERNAME_CAPACITOR_STAGE }}
        key: ${{ secrets.PRIVATE_KEY_CAPACITOR_STAGE }}
        port: 22
        script: bash .deploy
